version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - mongodb
      - minio
    env_file:
      - .env
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
      - MINIO_ENDPOINT=minio:9000
    networks:
      - vistascan-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - vistascan-network

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"
    networks:
      - vistascan-network

networks:
  vistascan-network:
    driver: bridge

volumes:
  mongodb-data:
  minio-data: